#!/bin/sh
main(){
echo "bamToBigWig "$inputbam" "$genomesize" "$outputbw
echo $(date '+%Y%m%d %H:%M:%S')
echo "bamtools coverage"
#bamtools coverage -in $inputbam -out $inputbam".cov"
echo "remove ramdom chrom and transform to bedGraph" 
sed -n '/^chr[0-9]*\t/p' $inputbam".cov" | awk '{print $1,$2,$2+1,$3}' > $inputbam".bedGraph"
echo "bedGraphToBigWig"
bedGraphToBigWig $inputbam".bedGraph" $genomesize $outputbw
echo "finish in "$(date '+%Y%m%d %H:%M:%S')
}

if [ $# != 3 ];then
    echo "usage : bamToBigWig input.bam genomesize output.bw"
    echo "Tips: Please add bamtools and bedGraphToBigWig to environment varibable and bam file should be sorted"
else
    inputbam=$1
    genomesize=$2
    outputbw=$3
    main
fi
~                                                                                                                                                                               
~        
